version: v4.43.0
slug: v2ray
name: v2fly-core
description: Visit the world beyond the Great Wall
url: https://github.com/banzhanglaolin/hassio-addons/blob/master/v2fly-core/
arch:
  - armv7
  - aarch64
  - amd64
  - i386
boot: auto
hassio_api: true
host_network: true
image: v2fly/v2fly-core
init: false
map:
  - config:rw
options:
  dirsfirst: false
  enforce_basepath: true
  git: true
  ignore_pattern:
    - __pycache__
    - .cloud
    - .storage
    - deps
  ssh_keys: []
startup: services
