version: v4.44.0
slug: v2ray
name: v2fly-core
description: Visit the world beyond the Great Wall
url: https://github.com/banzhanglaolin/hassio-addons/blob/master/v2fly-core/
arch:
  - armv7
  - aarch64
  - amd64
  - i386
boot: auto
image: banzhanglaolin/v2fly-core
init: false
startup: services
ports:
  10809/tcp: 10809
  10808/tcp: 10808
  10809/udp: null
  10808/udp: null
ports_description: 
  10808/tcp: "v2fly-core socks"
  10808/udp: "v2fly-core socks"
  10809/tcp: "v2fly-core http"
  10809/udp: "v2fly-core http"
options:
  loglevel: warning
  protocol: vmess
  address: null
  port: null
  id: null
  alterId: 0
  security: auto
  network: tcp
  type: http
schema:
  loglevel: list(trace|debug|info|notice|warning|error|fatal)?
  protocol: list(vmess)?
  address: str
  port: str
  id: password
  alterId: int
  security: list(aes-128-gcm|chacha20-poly1305|auto|none|zero)?
  network: list(tcp|kcp|ws|h2|quic|grpc)?
  type: list(none|http)?
