version: 4.43.0
slug: v2ray
name: v2fly-core
description: Visit the world beyond the Great Wall
url: https://github.com/banzhanglaolin/hassio-addons/edit/master/v2fly-core/
arch:
  - armv7
  - arm64
  - amd64
  - i386
hassio_api: true
host_network: true
image: v2fly/v2fly-core
init: false
startup: services
