version: v4.43.0
slug: v2ray
name: v2fly-core
description: Visit the world beyond the Great Wall
url: https://github.com/banzhanglaolin/hassio-addons/blob/master/v2fly-core/
arch:
  - armv7
  - aarch64
  - amd64
  - i386
boot: auto
hassio_api: true
host_network: true
image: v2fly/v2fly-core
init: false
options:
  loglevel: warning
  protocol: vmess
  address: 20.151.113.120
  port: 1426
  users_id: "e0f591b2-69a2-4e92-a0f3-d39a2f70b768"
  alterid:  0
  security: none
  network: tcp
schema:
  loglevel: str
  protocol: str
  address: str
  port: int
  users_id: str
  alterid:  int
  security: str
  network: str
startup: services
