version: v4.43.0
slug: v2ray
name: v2fly-core
description: Visit the world beyond the Great Wall
url: https://github.com/banzhanglaolin/hassio-addons/blob/master/v2fly-core/
arch:
  - armv7
  - aarch64
  - amd64
  - i386
boot: auto
hassio_api: true
host_network: true
image: v2fly/v2fly-core
init: false
map:
  - config:rw
options:
  {
    "inbounds": [{
      "port": 1080,  // SOCKS 代理端口，在浏览器中需配置代理并指向这个端口
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": true
      }
    }],
    "outbounds": [{
      "protocol": "vmess",
      "settings": {
        "vnext": [{
          "address": "server", // 服务器地址，请修改为你自己的服务器 ip 或域名
          "port": 10086,  // 服务器端口
          "users": [{ "id": "b831381d-6324-4d53-ad4f-8cda48b30811" }]
        }]
      }
    },{
      "protocol": "freedom",
      "tag": "direct",
      "settings": {}
    }],
    "routing": {
      "domainStrategy": "IPOnDemand",
      "rules": [{
        "type": "field",
        "ip": ["geoip:private"],
        "outboundTag": "direct"
      }]
    }
  }
startup: services
