version: v4.44.0
slug: v2ray
name: banzhanglaolin/v2fly-core
description: Visit the world beyond the Great Wall
url: https://github.com/banzhanglaolin/hassio-addons/blob/master/v2fly-core/
arch:
  - armv7
  - aarch64
  - amd64
  - i386
boot: auto
image: banzhanglaolin/v2fly-core
init: false
startup: services
ports:
  10809/tcp: 10809
  10808/tcp: 10808
  10809/udp: null
  10808/udp: null
ports_description: 
  10808/tcp: "v2fly-core socks"
  10808/udp: "v2fly-core socks"
  10809/tcp: "v2fly-core http"
  10809/udp: "v2fly-core http"
options:
  policy:
    system:
      statsOutboundUplink: true
      statsOutboundDownlink: true
  credential_secret: ""
  theme: default
  http_node:
    username: ""
    password: ""
  http_static:
    username: ""
    password: ""
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  system_packages: []
  npm_packages: []
  init_commands: []
schema:
  policy:
    system:
      statsOutboundUplink: bool
      statsOutboundDownlink: bool
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  credential_secret: password
  theme: list(default|dark|dracula|midnight-red|oled|solarized-dark|solarized-light)?
  http_node:
    username: str
    password: password
  http_static:
    username: str
    password: password
  ssl: bool
  certfile: str
  keyfile: str
  system_packages:
    - str
  npm_packages:
    - str
  init_commands:
    - str
  leave_front_door_open: bool?

