ARG BUILD_FROM
FROM $BUILD_FROM

WORKDIR /root
ARG TARGETPLATFORM
ARG TAG
COPY v2ray.sh /root/v2ray.sh

RUN set -ex \
	&& apk add --no-cache tzdata openssl ca-certificates \
	&& mkdir -p /etc/v2ray /usr/local/share/v2ray /var/log/v2ray \
	&& chmod +x /root/v2ray.sh \
	&& /root/v2ray.sh "${BUILD_FROM}" "${TAG}"

CMD [ "/usr/bin/v2ray", "-config", "/data/config.json" ]
